### ISSUE TITLE
Agile or Waterfall? 

### ISSUE THREAD

**Issue by eggsactly** [bspymaster/Evolution#134]
Was this project developed using agile or waterfall? 
I'm doing a research paper for my systems engineering class about development methodologies and I want to see if they have an impact on commit patterns.

**Comment by scytail** [comment]
This project was developed using agile. I'd be more than willing to help clarify any other questions you may have about it!

**Comment by eggsactly** [comment]
Ben, thank you for your reply. You can mark this issue as closed if you want. Although agile/waterfall may be a simplistic category, I plan to look at the commit patterns of many _many_ projects as part of my study to soften the variability between projects. I appreciate your response, your project will be an interesting data point to look at.

**Comment by scytail** [comment]
Glad I could help! Please let me know if I can be of any more assistance in the future.

**Comment by eggsactly** [comment]
@scytail would you mind filling out a survey about your experience on Evolution? It has 19 multiple choice questions. 
https://www.mysurveygizmo.com/s3/4945760/Product-Development-Methods-on-Engineering-Disciplines-Survey
My research team decided to issue a survey for our research project.

**Comment by scytail** [comment]
I wouldn't mind at all! I'll fill it out when I get the chance. Good luck with that research project.

**Comment by eggsactly** [comment]
Thank you @scytail !
