### ISSUE TITLE
GUI Sprites

### ISSUE THREAD

**Issue by Master-Ian** [bspymaster/Evolution#4]
Need Unity sprites for the following:
-Environment Tiles (Ocean, Lake, Grassland, Forest, Desert, Tundra, Mountains)
-Species Icons
-Information Windows
-Main Menu
-Gene Web

**Comment by scytail** [comment]
Talk to me about the UI design for the gene web, I found a picture online a week ago that I think would thematically go well with the project and would look good given the structure of the tree.
