### ISSUE TITLE
Remove Fish/Amphibian subtree options from the tree

### ISSUE THREAD

**Issue by scytail** [bspymaster/Evolution#6]
I have been talking to Tom (and a little to Ian) and we proposed that both Fish and Amphibians be removed from our evolutionary tree.

Right now the tree is separated into 5 different specialization subtrees: Mammals, Birds, Reptiles, Fish, and Amphibians. I am proposing this gets cut down to 3 subtress: Mammals, Brids, and Reptiles. There are a few reasons for this:

1. It makes the reptile species more defined in terms of unique characteristics. Mammals and Birds are very clearly defined and are unique in their own regards. However, Fish, Amphibians, and Reptiles are very similar in a lot of ways and seems to be more of a "spectrum" from Reptiles to Fish in how they are currently being built (with amphibians somewhere in the middle). If we remove Fish and Amphibians, we can add some of the more interesting characteristics into the Reptiles class (such as secreting poison onto their skin like frogs) and define reptiles easily.
2. It simplifies world generation and environment control. If we remove Amphibians and Fish, we can remove the need to make water a livable environment, and instead simply treat it as an environment control and a resource. There would be no need to invent an entire new ecosystem of food and environment variables for water, since it would be used as simply and environment variable itself, rather than it's own biome with complex ecosystem. It can still be used to control how animals flow (like restricting certain creatures that can't swim to a continent, or creating a focus point like an oasis in a desert), but it is not as complex a system to generate.
3. It makes game play for players more fair. If the player chooses fish, and chooses freshwater, and randomly gets placed in a small lake, their entire population is suddenly limited by that single lake. While this is theoretically still a good challenge for a player to have, I feel that it could be *too* limiting of a challenge, and to alleviate this, we simply remove the ability for them to HAVE to live in the water. (Note that because of this, mammals such as dolphins and whales would also be hard if not impossible to recreate.)
4. It makes the web simpler and more intuitive. Right now I am juggling around tons and tons of ideas for various paths and evolutionary traits to add to the tree. Removing these two branches effectively cuts out 1/3 of my work, which would help a lot. Additionally, by removing these two branches, it will help players (especially new players) be able to figure out the tree a little faster and easier, and focus in on what specialized traits that want more than if there were 5 subtrees.

Thoughts? Concerns? Objections?

**Comment by Master-Ian** [comment]
I agree with this idea.  If nothing else it will simplify the web, thus letting us delegate more time and effort on other aspects of the project.  I feel like going overboard with just the web is a bad idea, at least until we can get a working Alpha of the game.

**Comment by scytail** [comment]
I agree. Depending on how the project progresses, we may even want to postpone finalizing the web (once I get a functional baseline complete) until other aspects are finished.

**Comment by Futhark491** [comment]
I like this change personally.  Just looking at how the world would be built the player would suddenly find themselves in two potential situations.  First they are spawned in a puddle which that would almost for sure be boring to play out since you would either have to stay in the puddle or evolve out.  The second situation I can think of is that due to ocean/lake tiles being super picky on what can live in them the AI would have to randomly evolve into being a fish/amphibian to try to put pressure on the player. Both situations would be pretty boring in my opinion.

**Comment by scytail** [comment]
Alright. I'll crop those branches out and continue.
